language: node_js
node_js:
- '10'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: IfwQMdgTU9dZtDFTh5HX0Q3QyP+/JV0hV1EwuYvBfuM2St/TiSJqaiUMXHqVM2PzQJlNzn6t5rWgUFNZRNxNB9+IZyPJL83+ZhwWTweQ0xJw6wlPhvy+m17u89OGEliduAX8lhmfX1jeIM3z/4+fOhEUF7zgCXZVP58Xk9iUHOnawb1jj/7FZPNkAYXugtVauf/Z2/Nz9V/FkzquIlZ7tG7DlZeHQtf1VE7ilsImbWAo35MaY/XudzWbX9e7f5DlbMuCwKMuIu0Fke55pU+VQ2AVZ3A6ThniLNnmz0ElnwbTyNKUv/P5Gt68AhoZCgP0UfoKGno3tVJeCX5trOkP1YQUND5XJigyqb63ZUUgS642fDdRLsPtp5ovL8qyCLkzBUXAw4QN7i5uan9SuINwzPkuSCDaCbJP/HvtGd1s9l+A3Wv06f/R2CqXb29wIWfVKvZVjY5l5HXqGDvDprFRkztQlVI5XNZQQqIaaVeeW5ornqBfPnZxoY9fhrc3tXjVugsr/hJtKIRbHRdYH0mPnv+2+4pBsahpu8AQKYp7c8Hy69sUkbaRTgoQ+Jv4QTMh0KmZ2X+x9UJyaBw7Sk1Nc7Ra6GmHi37SxUlKn+5zOztpfsvNpdrzXjXbsG4X7EEJj13Y+O+GYEjICh/EZcePOQ/qwdG+qmh44EQzGKMzlOM=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/with-raf
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: SKkEK2t3AZIQ01ZQHWYweyqLdUZoVMLAenUon9diRWL+VgIcXGoag10wMjO6XF12aUJRG+uz/a53/5nsug04hE7xxadV6gHXKSt0WIjHnwV7ZtV747gHGuCu/h8BLemonZzYXgHV4y+gqi8c6PZga5mLC/ugFPn06+vYEszAld2F6suasRSGxv7+oCNyKYqJjmBnoZfwIFc3t3DrDXqw1ZreER1+Ax4Td5opQ1m5LdumqeXBiX5aznDzwNMm/SvBd3LtG7m/GDJ1bj/bEQZ0HHYP48hz5gO2m6WNIrvPP66ngDNOjuRvbN5MWt7Z2SuYOJn1hNovjXd2hZ1qqKwiegC1Cuvhx62ZyFAID3dP6ozkawGnzqot8JZyk+yi5OodCvG0QKYLhUVJduaYWFO25eHMdrqUD8sX8XJVxBxGfeaFowKU67bBLYWC8RaRqtZg+5SvMf80Pt+9/fk2j2eW5ueMQK0R4L3mq6pzJttdyq4mvxtXQPxtz7UW8IFub4dTpLfmg44LkLojS/LuMpiTPAjikbk7fLDINBHUKvugJNkCrr8Z0w67snpzq2dZO8c7U7jNxhAYymwIw4p3IszXjCm5iIfmV96QHmUYaaYjDWScvRijVdCBrp2Gcb8TwqwiXmkzuhBQeMh58vuCm0ba4kj7xwweAbr1+zflpdC/2mQ=
    on:
      branch: master
      tags: true
      repo: flekschas/with-raf
