language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: kprDKDgtYP6sdDZ1TzoTxbGgv9l6ds9aWScLbeVqXPkPr+SCEEW0Bcg3Fr6NLasCXxcv128QCtLQI9yVbCDF5k0Z8MldrYL9JMRLwFhnEymnWQhbNB5oU3nZl5N2LlfqNF/fpLw9nbDv2V+474s+Lj98h+qOullG/Bm8ShfFgOY2ZbF6UG4DQQltRMHWK+iLqvkiZncm8fdFRwTxsBtpiNxr9elQy94lG9yDQN17w82jZnOOwmVQnMGz721X1q6OiBGMozS2uwJQLJX+vZcEfTro3M5TFurc8mWQG/SMC7R7iVz0HIo0IFOSDS8CnaxUSSBsMfjLC7Z+tc6Ni5aI8oZM96I0XxFqsPPLbxUbbcvtwIw28ux3okIZMfFSIlsMTFJ2zSGLxHOnEHJzkJ9R3iKuVldW9ObWzwvdUt+2QzERjVGWXKqr4j4I2ugBwQ6brqsR707jrsH7L99hqbk+EMivx+eF2Y0f9WDa29iovy9PkmolZcC7GAtrqkyIK/09z1+bbXTpE/hAiXDsHZyl9wGPueQ2NCRkPIotgo/EsydX+klZb2ld0YYyaWK1+VTjOFOHpcEahG9Iynj0kM8CB7FwsHYbn9PNNOQyjiUugVAIsfdeIChzOXDa6BVeDkbkLJWJlag9mL+Ck5TTaFLp1325p7TU8kCPVup0GWZOLfU=
    file: dist.zip
    on:
      branch: master
      tags: true
      repo: flekschas/with-raf
  - provider: npm
    skip_cleanup: true
    email: service@lekschas.de
    api_key:
      secure: meU0QP44UvUe8HHMUJ0eOH1cCTlJZBCRqoXQ68HiMuoLYO3VvO+NFaMgaaktE5JZMtzPY8CZ3CSTn8UMIpP31zpVYIGmzH3RQY+ZvlOW/QO06fRbZeRdfYCoMAnFpzk9athxfK/Ek39bsf4SRcoHt2VZk7Oii0unFH2gE29ZOg709Bd9BOPW0NM53mhhdKCxAjixxkwNQQd3Qfgi+47RBEhewMz3xvmNoWvhRXukalREUD+tXKX3dcAH/huiuLUUysxRNzJvjxXidFgP1ob+dyeb61MGCIo53Kn65AnLI4N/VKUfnx81ALsbDnus5tzRYQnsLOkehv6iqAcF8oVn0C1/pmPzHE0ZorZ8HvhFWweCHx8X6MqTAjU9Bjw3lxj6nkgSNA/QOydSGvIwoN6ybofjtZURDdwKZuXYo0GspOpFZayCc5rKJtOl3h3nnaJH00F92dotB48rWug2a5DioGCuRF3jci+bUuFRX5Hb25DMJoWd3xSmj98fzIguzFpsDhv3XoWkz5iTqaknGX0DJxbJgEG1XSFsy6Jmcuz5lPuC1CacDT9n2tcca4kRUpk6lZ6f9G2iZ0SVVOqvPtlYWuFxZXjrZlk7QdHYZ9CkxEAV98P3b/iF9n3Va0C4NYEXYVBDRtn7GGncX/exI+2Wty5xbgyIEGYmnaUW7h1CE1M=
    on:
      branch: master
      tags: true
      repo: flekschas/with-raf
